### ISSUE TITLE
Lifesteal bug

### ISSUE THREAD

**Issue by TeamNexium** [Taiterio/ce#10]
Hey I'm not sure if I'm commenting in the right place (still new to Github) 
Anyways, I found a bug in the Lifesteal class line 53

Right now it's taking 'newheal' which is what should be the new value and it's adding the current hp, making it over the max hp. simply change it to 
damager.setHealth(newheal);  

Hope I helped :3

**Comment by Taiterio** [comment]
Yeah, fixed that yesterday and will push out an update today, thanks for marking it here though :)
