### ISSUE TITLE
Enchant Swords with Global Enchants even without enough money.

### ISSUE THREAD

**Issue by scriptinator** [Taiterio/ce#17]
People can enchant swords with global enchants, even if they don't have enough money to buy it. It only works with swords on global enchants.

**Comment by Taiterio** [comment]
Will look into it

**Comment by scriptinator** [comment]
Any status on where the bug is coming from?

**Comment by Taiterio** [comment]
Could not reproduce this bug, can you give me a list of plugins that are running when this behavior occurs?

I have had reports of this occuring with ANY enchantment type, not just global ones, so this seems very odd o.O

**Comment by scriptinator** [comment]
I don't know, but it seems with only global

**Comment by Rida94** [comment]
I have the same issues, but with all enchantments and items, it will say no enough money, but still add the enchantment. using spigot and the plugin latest versions today. there is no console bug.

**Comment by Taiterio** [comment]
Please try again in version 2.4
