### ISSUE TITLE
Compiling from Github Error

### ISSUE THREAD

**Issue by SolarShrieking** [Taiterio/ce#19]
ArrayIndexOutOfBoundsException: 4 when running built jar from github resource.

Libraries:
Craftbukkit 1.8.8
Vault
Worldedit 6.1
Worldguard 5.9

Attempted using both JDK 1.7.0_79 and the latest 1.8 JDK. 
No errors in IntelliJ on compile, only during runtime on a test server.
http://pastebin.com/562m7ds5

**Comment by DrkMatr1984** [comment]
This looks like a config generation error. Regen config and see if this still happens.

**Comment by SolarShrieking** [comment]
Yes, it still happens. However, I am noticing that the final line in the default config, "Enchantments:" is missing when it generates.

**Comment by SolarShrieking** [comment]
Built using a different IDE, works fine. Thanks anyway, DrkMatr1984! :)

**Comment by DrkMatr1984** [comment]
OK Cool :) Glad this is resolved.

**Comment by DrkMatr1984** [comment]
Yeah it was occurring because it could not build the list of enchantments in the config. Usually after the Enchantments line it begins listing the enchantments and their options. For some reason your original copy was not building this section correctly.
