### ISSUE TITLE
Console Error when Enchanting

### ISSUE THREAD

**Issue by astr1al** [Taiterio/ce#20]
For some reason I get this spammed in my console every time someone enchants something

http://pastebin.com/0cNFQSgC
Using spigot 1.8.8

**Comment by Taiterio** [comment]
This is because your CEnchantingProbability is a float, while i should be an integer. The enchanting system will be reworked eventually to allow more sophisticated enchanting chances.

**Comment by Taiterio** [comment]
Fixed in b763da27bd32dc040c8528a2584bcd17d619023d
