### ISSUE TITLE
ce menu error 

### ISSUE THREAD

**Issue by joshua31177** [Taiterio/ce#21]
the item menu part of the ce menu is broken and i have a repeated error in my server log  which strangely  disapeared.
![2016-02-05_18 30 55](https://cloud.githubusercontent.com/assets/12284394/12870849/6be6ff36-cd1d-11e5-9777-8af568546d62.png)

**Comment by Taiterio** [comment]
CE does not have a fallback that would ever create items with the name "ITEM NAME NOT FOUND", much less reset the material to the wooden sword, so it seems like a different plugin is interfering here.

Please check for plugins that might want to restrict unique item names or fall into a similar category as CE.
