### ISSUE TITLE
making moreitems compatible with custome enchantments 

### ISSUE THREAD

**Issue by joshua31177** [Taiterio/ce#22]
i think that the plugin moreitems is what caused my previous problem is it posible to make it work with custom ehcnatments?  

http://dev.bukkit.org/bukkit-plugins/moreitems/

**Comment by Taiterio** [comment]
Adding the Custom Enchantments to the lore will work, although this seems to be the only way that CE will work with MoreItems. I don't see any way to make it more compatible from CEs side though :/
