### ISSUE TITLE
Drag And Drop Help

### ISSUE THREAD

**Issue by GamingEasee** [Taiterio/ce#34]
I can not figure out how to make my custom enchantments book able to be dragged and dropped on to a item.
For example
I have a bow and a piercing book in my inventory how can i make it to were i can drag the book to the bow and click it down on the bow and it is applied to the bow

**Comment by Taiterio** [comment]
Drag and drop is not a feature of Custom Enchantments, instead it uses a feature called [Runecrafting](http://dev.bukkit.org/bukkit-plugins/custom-enchantments/#w-enchantment-books)
